# docker-compose.yml
version: '3'
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - '8086:8086'
    volumes:
      - .dockscope/backend/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=dockscope
      - DOCKER_INFLUXDB_INIT_BUCKET=dockscope-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken123
